# - name: Creates directory
#   become: true
#   file:
#     path: /home/ubuntu/
#     state: directory

- name: "move binary to /backend."
  become: true
  copy:
    src:  /root/project/app.tar.gz
    dest: /home/ubuntu/
    #    directory_mode: yes
    #    mode: '0777'
  
- name: "Unpack app.tar.gz files"
  become: true
  shell: |
    cd /home/ubuntu/
    tar xzvf app.tar.gz
  #     rm app.tar.gz
  #     ls
- name: "move .env to /backend."
  become: true
  copy:
    src:  /root/project/backend/.env
    dest: /home/ubuntu/backend

# - name: Executing node
#   become: true
#   shell: |
#     pm2 start /home/ubunt/backend/dist/main.js -f
