# - name: Creates directory
#   become: true
#   file:
#     path: /home/ubuntu/
#     state: directory

- name: "move binary to /backend."
  become: true
  copy:
    src:  /root/project/app.tar.gz
    dest: /home/ubuntu/
    #    directory_mode: yes
    #    mode: '0777'
  
- name: "Unpack app.tar.gz files"
  become: true
  shell: |
    cd /home/ubuntu/
    tar xzvf app.tar.gz
  #     rm app.tar.gz
  #     ls
- name: "move .env to /backend."
  become: true
  copy:
    src:  /root/project/backend/.env
    dest: /home/ubuntu/backend

- name: Install Node modules
  shell: |
    cd /home/ubuntu/backend
    npm install

- name: Building backend service
  shell: |
    cd /home/ubuntu/backend
    npm run build
    npm run prestart:prod
        
- name: Executing node
  become: true
  shell: |
    cd /home/ubuntu/backend
    pm2 start npm --name backend -- start
    pm2 ls

- name: start pm2 for dist/main.js
  become: no
  shell: pm2 start main.js
  args:
    chdir: /home/ubuntu/backend/dist